#!/bin/bash
# Simple DNS maker for BonvScripts

# Decrypt pa more
# %d/%m/:%S

if [[ $EUID -ne 0 ]];then
 ScriptMessage
 echo -e "[\e[1;31mError\e[0m] This script must be run as root, exiting..."
 exit 1
fi

find / -iname 'UbuntuVPS-Installer'
if [[ "$(echo $?)" -ne 0 ]]; then
 echo -e " This script is usable only for BonvScripts Ubuntu VPS Installer script, exiting..." && exit 1
fi

IPADDR="$(curl -4sSL http://ipinfo.io/ip)"
PAYLOAD="www.viber.com.edgekey.net"
KEYNAME="bonvscripts-ubuntuvps"
COUNTER="$(curl -sX GET "https://api.countapi.xyz/hit/BonvScripts/UbuntuVPS-Installer" | jq -r '.value')"

# -e 's/#.*$//'  
# -e '/^$/d'

SELECT_DNS="$(head /dev/urandom | tr -dc '1-4' | fold -w 1 | head -n1 | uniq -i | sort -n)"

case "$SELECT_DNS" in
 1)
GLOBAL_API_KEY="695a1df17f42b424a47cb4ebe15370bbb565c"
CLOUDFLARE_EMAIL="bonveizen@emailcorner.net"
DOMAIN_NAME_TLD="bonvcdn1.gq"
DOMAIN_ZONE_ID="738adefdfa645bea312ea08618119dc1"
 ;;
 2)
GLOBAL_API_KEY="695a1df17f42b424a47cb4ebe15370bbb565c"
CLOUDFLARE_EMAIL="bonveizen@emailcorner.net"
DOMAIN_NAME_TLD="bonvcdn2.gq"
DOMAIN_ZONE_ID="b9c27635e3454abe2c839be039c47bc2"
 ;;
 3)
GLOBAL_API_KEY="695a1df17f42b424a47cb4ebe15370bbb565c"
CLOUDFLARE_EMAIL="bonveizen@emailcorner.net"
DOMAIN_NAME_TLD="bonvcdn3.gq"
DOMAIN_ZONE_ID="b295fed7fe47c1e705ebe04125a34d06"
 ;;
 4)
GLOBAL_API_KEY="695a1df17f42b424a47cb4ebe15370bbb565c"
CLOUDFLARE_EMAIL="bonveizen@emailcorner.net"
DOMAIN_NAME_TLD="bonvcdn4.gq"
DOMAIN_ZONE_ID="78f5be7b8ba434a0aba77d3d1998a634"
 ;;
esac

####
## Creating file dump for DNS Records 
TMP_FILE='/tmp/abonv.txt'
curl -sX GET "https://api.cloudflare.com/client/v4/zones/$DOMAIN_ZONE_ID/dns_records?type=A&count=1000&per_page=1000" -H "X-Auth-Key: $GLOBAL_API_KEY" -H "X-Auth-Email: $CLOUDFLARE_EMAIL" -H "Content-Type: application/json" | python -m json.tool > "$TMP_FILE"

## Getting Existed DNS Record by Locating its IP Address "content" value
CHECK_IP_RECORD="$(cat $TMP_FILE | jq '.result[]' | jq 'del(.meta)' | jq 'del(.created_on,.locked,.modified_on,.proxiable,.proxied,.ttl,.type,.zone_id,.zone_name)' | jq '. | select(.content=='\"$IPADDR\"')' | jq -r '.content' | awk '!a[$0]++')"

cat $TMP_FILE | jq '.result[]' | jq 'del(.meta)' | jq 'del(.created_on,.locked,.modified_on,.proxiable,.proxied,.ttl,.type,.zone_id,.zone_name)' | jq '. | select(.content=='\"$IPADDR\"')' | jq -r '.name' | awk '!a[$0]++' | head -n1 > /tmp/abonv_existed_hostname

cat $TMP_FILE | jq '.result[]' | jq 'del(.meta)' | jq 'del(.created_on,.locked,.modified_on,.proxiable,.proxied,.ttl,.type,.zone_id,.zone_name)' | jq '. | select(.content=='\"$IPADDR\"')' | jq -r '.id' | awk '!a[$0]++' | head -n1 > /tmp/abonv_existed_dns_id

## Setting variable

function ExistedRecord(){
 MYDNS="$(cat /tmp/abonv_existed_hostname)"
 MYDNS_ID="$(cat /tmp/abonv_existed_dns_id)"
}


### Creating a DNS Record
function CreateRecord(){
TMP_FILE2='/tmp/abonv2.txt'
curl -sX POST "https://api.cloudflare.com/client/v4/zones/$DOMAIN_ZONE_ID/dns_records" -H "X-Auth-Email: $CLOUDFLARE_EMAIL" -H "X-Auth-Key: $GLOBAL_API_KEY" -H "Content-Type: application/json" --data "{\"type\":\"A\",\"name\":\"$KEYNAME.v$COUNTER.$PAYLOAD\",\"content\":\"$IPADDR\",\"ttl\":1,\"proxied\":false}" | python -m json.tool > "$TMP_FILE2"

cat "$TMP_FILE2" | jq '.result' | jq 'del(.meta)' | jq 'del(.created_on,.locked,.modified_on,.proxiable,.proxied,.ttl,.type,.zone_id,.zone_name)' > /tmp/abonv22.txt
rm -f "$TMP_FILE2"
mv /tmp/abonv22.txt "$TMP_FILE2"

MYDNS="$(cat "$TMP_FILE2" | jq -r '.name')"
MYDNS_ID="$(cat "$TMP_FILE2" | jq -r '.id')"
}



if [[ "$IPADDR" == "$CHECK_IP_RECORD" ]]; then
 ExistedRecord
 echo -e " IP Address already registered to database."
 echo -e " DNS: $MYDNS"
 echo -e " DNS ID: $MYDNS_ID"
 echo -e ""
 else
 CreateRecord
 echo -e " Registering your IP Address.."
 echo -e " DNS: $MYDNS"
 echo -e " DNS ID: $MYDNS_ID"
 echo -e ""
fi

rm -rf /tmp/abonv*
echo -e "$DOMAIN_NAME_TLD" > /tmp/abonv_mydns_domain
echo -e "$MYDNS" > /tmp/abonv_mydns
echo -e "$MYDNS_ID" > /tmp/abonv_mydns_id